"""Build-time ERBA artifact trust anchors; generated by prepare_erba_app_assets.py."""
from __future__ import annotations

TRUSTED_ERBA_ARTIFACTS: dict[str, dict[str, object]] = {
    "classification:er_alpha": {
        "candidate_registry_sha256": "5e9568c18c61b6c624aa09ade9ab8750c8fe61dc39ca5324e8547bf31417b942",
        "caveat_sha256": "3890a69b45c235b35bd4bbbeb9e05ea0d86c17276f0931551f74be7d80929c9b",
        "evidence_scope": "internal_historically_exposed",
        "historical_exposure_manifest_sha256": "3dd33f9db3de05212b5a46fb052f609f9f3be7701c2788ffcee9a9493c18db3c",
        "internal_resplit_sha256": "6f30c84d445ab530c1daaf816972f15af2e86b21c88ce0238f4bf81a7ef106cc",
        "model_id": "erba_classification_v7_er_alpha",
        "nested_cv_sha256": "0a8d283c29723401619ee69c0a9d9bb29cc63604b82bdf8497668e506fc146fc",
        "protocol_sha256": "406da317873c99882cab4f07f280ecacca26e1f1fa47d70822e6c446835ffe6d",
        "release_manifest_relative_path": "release_manifest_ERalpha.json",
        "release_manifest_sha256": "b5799c3ec45a2a2ccd5a2975d89cac8a9a5d40a73ad186f14de27e43325c9918",
        "release_status": "released",
        "report_sha256": "6c49f6858743e0b8c1ad419c4415601668e3d22ff6c9733335aea0eacc69beb6",
        "sha256": "db3f2c369cfc9f2a08ecc985424879b70b82f3a4bc8d11a5e2f94ab8c7fe96ea",
        "size_bytes": 11743515,
        "source_manifest_sha256": "63e890935aab3afae78ebf6bc3c120140677b87218753e8fa15571ad9068d0d5",
        "split_manifest_sha256": "9d2299a90de30fba4763fd63e11d69898a92a9b7c461e6762e95c131f6c00582",
        "transformer_source_sha256": "8e366b6c37950499d08162d88f08a93f6373cb15e92105bc612854b782846f78"
    }
}
